### ISSUE TITLE
Could you send RioShiina prebuilt?

### ISSUE THREAD

**Issue by fluffyloopy** [Yggdrasill-Moe/Niflheim#18]
I have no idea how to build c or c++ files and i've got to this point 
![image](https://user-images.githubusercontent.com/36381994/98482979-cd18fa80-2226-11eb-9896-0e1ba4074826.png)
So i was wondering if you could tell what i'm supposed to do here or send a prebuilt.

**Comment by Darkness-TX** [comment]
You can use visual studio to build.
But these programs are only used for "BLOODY RONDO" which version is 2.48 in RioShiina engine,because different version or game which in RioShiina engine has different key and decrypt image,decrypt image can found in exe.
In a word, the unpacking and packing of this engine is very troublesome, so there are only a few tools on the network, and they are no universality. It needs to be made for different versions and games.
The other RioShiina project which is use inline hook:https://github.com/jszhtian/Fragment/tree/master/RioShiinaPatch
[BLOODY RONDO.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/5507462/BLOODY.RONDO.zip)

**Comment by fluffyloopy** [comment]
Yeah, doesn't work on onikuru. Thanks for the info and file tho
