### ISSUE TITLE
Shiina Rio : Nukitashi2 support for special files

### ISSUE THREAD

**Issue by MrShiruba** [Yggdrasill-Moe/Niflheim#36]
Hello I'm sorry to open an issue for a game that was already dealt with but I've downloaded the provided link for "NUKITASHI2.zip" on a previous issue : https://github.com/Yggdrasill-Moe/Niflheim/issues/23
This tool seems to work on most of the files except for the main files named "NUKITASHI2_V1.WAR" and "NUKITASHI2_V2.WAR". Are they encrypted differently? Or maybe the tool should work with these and my files are different somehow?

Here is a link for the files that works(NUKITASHI2_S.WAR or NUKITASHI2.WAR) and that don't work (NUKITASHI2_V1.WAR and NUKITASHI2_V2.WAR) : https://drive.google.com/file/d/1oNm5Hs2S6674ok4szRvgQlUazw8pO34U/view?usp=sharing

I know how to program in C but don't know how to program in assembly (though I know what this is).

**Comment by Darkness-TX** [comment]
Because the total number of files which in NUKITASHI2_V1.WAR is 7918, there is not enough memory.
change WARC_Info[5000] to WARC_Info[50000].

I didn't use linked list to store indexes because of my lazy habit, sorry. :)
[NUKITASHI2_fix.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/9691724/NUKITASHI2_fix.zip)
