### ISSUE TITLE
Something wrong with gyu_tool

### ISSUE THREAD

**Issue by Cosetto** [Yggdrasill-Moe/Niflheim#45]
Maybe these two images are one
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/5052832e-aedc-4dab-abc8-7d9c7df46caf)
[gyu_image.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12415874/gyu_image.zip)

**Comment by Darkness-TX** [comment]
ExHIBIT project didn‘t have complete test.(That's why didn‘t have rld_text_input.py, only have rld_text_output.py)
It will take one or two days to repair.
Temporary repair program for 32bpp.
[gyu2png.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12428343/gyu2png.zip)

**Comment by Cosetto** [comment]
Thanks, but can you also fix png2gyu too?

**Comment by Darkness-TX** [comment]
[newgyu.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12447151/newgyu.zip)

**Comment by Cosetto** [comment]
Thank a lot man

**Comment by Cosetto** [comment]
Another bug with new gyu_tool
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/b6c61ce8-185c-4081-a1ee-f0c7c3c26c88)
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/3461c8c3-0f15-4293-a93b-442ffde3911c)
[gyu.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12511917/gyu.zip)

**Comment by Darkness-TX** [comment]
gyu2png:
Line 146:
png_data_down[j * gyu_header.width * 4 + i * 4] = pal_data[dst_data[j * ((gyu_header.width * gyu_header.bpp / 8 + 3) & ~3) + i] * 4];
Line 148:
png_data_down[j * gyu_header.width * 4 + i * 4 + 2] = pal_data[dst_data[j * ((gyu_header.width * gyu_header.bpp / 8 + 3) & ~3) + i] * 4 + 2];

png2gyu:
no change

**Comment by Cosetto** [comment]
> gyu2png: Line 146: png_data_down[j * gyu_header.width * 4 + i * 4] = pal_data[dst_data[j * ((gyu_header.width * gyu_header.bpp / 8 + 3) & ~3) + i] * 4]; Line 148: png_data_down[j * gyu_header.width * 4 + i * 4 + 2] = pal_data[dst_data[j * ((gyu_header.width * gyu_header.bpp / 8 + 3) & ~3) + i] * 4 + 2];
> 
> png2gyu: no change

Lol, the color is different
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/77bf97dc-b4cd-4a5d-a983-5260c6b772f5)

**Comment by Darkness-TX** [comment]
May be no bug?
I compiled the code without any changes,then running correctly.
It seems that there is a problem with the file which I gave you in newgyu.zip……
You can compile the code by yourself.
Re-compiled exe:
![2023-09-06 13 42 01](https://github.com/Yggdrasill-Moe/Niflheim/assets/22828117/e23cd837-9382-4ccd-9603-6a8e425e2fc1)
gyu2png.exe in newgyu.zip:
![2023-09-06 13 44 54](https://github.com/Yggdrasill-Moe/Niflheim/assets/22828117/e7684f17-6c45-4df8-a01d-4f36c3e7c4ef)

**Comment by Cosetto** [comment]
Org:
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/2ea4e6ce-8f9a-40c2-918b-bed65c9b3986)
New:
![image](https://github.com/Yggdrasill-Moe/Niflheim/assets/81801486/60d35846-afd7-4884-812e-8e683a0e2bf6)
Hm, I don't if this is because of the engine or gyu_tool?

**Comment by Darkness-TX** [comment]
I think I must download this game for test.

**Comment by Cosetto** [comment]
> I think I must download this game for test.

[Link](https://www.h-suki.com/en/games/2862)

**Comment by Darkness-TX** [comment]
Because of the engine, must be an Index8 gyu if the original gyu‘s bpp is 8, can't convert to 32rgba gyu.
[png2gyu.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12545180/png2gyu.zip)
Will update the code later.
Test:
[00_001.gyu.png.zip](https://github.com/Yggdrasill-Moe/Niflheim/files/12545230/00_001.gyu.png.zip)
![2023-09-07 13 53 20](https://github.com/Yggdrasill-Moe/Niflheim/assets/22828117/23cd9aff-b99d-49ed-bb84-b6c3fe5ea50f)

**Comment by Cosetto** [comment]
Thank you

**Comment by Cosetto** [comment]
@Darkness-TX Hokorisama in the latest issue is a chatgpt mtl user. So it would be best to ignore him.

**Comment by suphamster** [comment]
@Darkness-TX, can you look plz at 1920_290.gyu image and fix gyu2png tool if possible? 1st one converted with your gyu2png, 2nd one converted with gyu2bmp and 3rd file is original compressed to zip gyu file with which I have problem (english game name is "Welcome to a Sexy Open World" and there are a lot of files that have such problem). First output image is wrong because have only transparent background, 2nd as it should look for real (GARbro also unpacks it to png fine and looks like original image don't have alpha channel). But some other images (like inside 00090027P000.zip) GARbro also fails to convert correctly (look fine in image viewer but in game it becames white, maybe it's because I didn't converted png to gyu back and just renamed it).
![Image](https://github.com/user-attachments/assets/129ea3b9-def3-4bbb-8c73-e0650dc4c7e3)

![Image](https://github.com/user-attachments/assets/b83eaa80-188d-4ace-bfa2-93af03d5bf5f)

[1920_290.zip](https://github.com/user-attachments/files/18782132/1920_290.zip)

[00090027P000.zip](https://github.com/user-attachments/files/18803934/00090027P000.zip)
